name: Deploy Backend

on:
  push:
    branches:
      - main

    paths:
      - 'Backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Backend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}

          local-dir: ./Backend/
          server-dir: /rambhaji.backend.shreenari.com/

          dangerous-clean-slate: false

          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/.env
            **/*.zip
            **/uploads/**
            **/.vscode/**
            **/.idea/**
            **/README.md