name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build

      - name: Deploy dist via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}

          local-dir: ./Frontend/dist/
          server-dir: /rambhaji.frontend.shreenari.com/

          dangerous-clean-slate: false

          exclude: |
            **/.git*
            **/.github/**
            **/.env
            **/*.zip
            **/.vscode/**
            **/.idea/**
            **/README.md
            **/.DS_Store